name: Release test_rai_utilities to PyPI

# trigger manually only ("collaborator" or more permissions required)
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Test or Prod PyPI?"
        required: true
        default: "Test"

jobs:
  release-test_rai_utilities:
    runs-on: ubuntu-latest
    steps:
      - name: fail if Test nor Prod
        if: ${{ ! (github.event.inputs.type == 'Test' || github.event.inputs.type == 'Prod') }}
        run: |
          echo "Only Test or Prod can be used."
          exit 1

      # build wheel
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: update and upgrade pip, setuptools, wheel, and twine
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine

      - name: install requirements.txt for test_rai_utilities
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        working-directory: test_rai_utilities

      - name: pip freeze
        run: pip freeze

      - name: build wheel for test_rai_utilities
        run: python setup.py sdist bdist_wheel
        working-directory: test_rai_utilities

      # run tests before publishing to PyPI

      - name: install test_rai_utilities wheel locally
        run: find ./dist/ -name '*.whl' -exec pip install {} \;
        working-directory: test_rai_utilities

      - name: run test_rai_utilities tests
        run: pytest ./tests/
        working-directory: test_rai_utilities

      # publish to PyPI
      - name: Publish test_rai_utilities package to Test PyPI
        if: ${{ github.event.inputs.type == 'Test' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN_RAIUTILS }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: test_rai_utilities/dist/
      - name: Publish test_rai_utilities package to PyPI
        if: ${{ github.event.inputs.type == 'Prod' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_RAIUTILS }}
          packages_dir: test_rai_utilities/dist/
